# -*- coding: utf-8 -*-
"""aula_pandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T4qNgK8UViy1L7LorQR0Mx262sTdXRpx
"""

import pandas as pd

df = pd.read_excel('./system_extraction.xlsx')

df

df.head(5)

df=df.drop(columns=['Região', 'Preço'])

df

df.loc[df['Vendedor']== 'Paulo']

df.loc[df['Vendedor']== 'Paulo', ['Valor Pedido']]

df.groupby(['Produto vendido']).sum()

len(df)

df['marg_porc'] = 100*df['Margem Lucro'] / df['Valor Pedido']

df

df['Nº pedido'].where(df['marg_porc']>20, "menor que 20")

df['Cliente'].unique()

df['Cliente'].nunique()

df.nunique()

df['Nº pedido'].sort_values(ascending=False)

df.sort_values(by='Nº pedido', ascending=True)